### ISSUE TITLE
Bug Animação de Herói e Spotify

### ISSUE THREAD

**Issue by mariobrossteam** [LeoLeal/HotSCompanion#4]
Olá!

Quando vou visualizar a animação de um Herói enquanto o Spotify está tocando uma música, o Spotify é pausado. É parecido com o que ocorre quando se abre o Youtube durante a utilização do Spotify e este último é pausado temporariamente. Porém notei que no caso do Hots Companion, o Spotify é interrompido e não volta a funcionar automaticamente, mesmo que o Hots Companoin seja fechado. 

Obs: Este problema foi encontrado na plataforma IOS. 

Grato.

**Comment by LeoLeal** [comment]
Duplicado: #2

Obrigado por confirmar o bug no iOS!
